# ArgoCD in the Talos cluster.
#
# Its own root module with its own state key. The target cluster comes from
# var.kubeconfig_path, which points at the kubeconfig generated by talhelper
# under kubernetes-homelab/talos/clusterconfig/. That file contains only this
# cluster, so an apply cannot reach any other one.

terraform {
  required_version = ">= 1.0"

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = ">= 3.0.0, < 4.0.0"
    }
  }
}

provider "helm" {
  kubernetes = {
    config_path = var.kubeconfig_path
  }
}

resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  version          = var.argocd_chart_version
  namespace        = "argocd"
  create_namespace = true

  # Wait for the pods to be ready. Without this the apply reports success while
  # the server is still starting, and the root-app apply that follows it fails.
  wait    = true
  timeout = 900

  # ArgoCD's built-in default exclusion list, minus core/Endpoints.
  #
  # An excluded resource does not exist as far as ArgoCD is concerned: it is
  # never created and the Application still reports Synced/Healthy. The nine
  # hand-written Endpoints objects in manifests/external-services/ need
  # core/Endpoints to stay off the list.
  #
  # discovery.k8s.io/EndpointSlice stays excluded. Those slices are generated by
  # the mirroring controller, are owned by nothing in the repo, and are the bulk
  # of the volume.
  #
  # The list is pinned to the state of ArgoCD 3.5.0. On an ArgoCD major, compare
  # against the new default ("argocd admin settings resource-overrides list" or
  # the shipped argocd-cm) and update it here.
  values = [<<-EOT
    configs:
      cm:
        resource.exclusions: |
          - apiGroups:
            - discovery.k8s.io
            kinds:
            - EndpointSlice
          - apiGroups:
            - coordination.k8s.io
            kinds:
            - Lease
          - apiGroups:
            - authentication.k8s.io
            - authorization.k8s.io
            kinds:
            - SelfSubjectReview
            - TokenReview
            - LocalSubjectAccessReview
            - SelfSubjectAccessReview
            - SelfSubjectRulesReview
            - SubjectAccessReview
          - apiGroups:
            - certificates.k8s.io
            kinds:
            - CertificateSigningRequest
          - apiGroups:
            - cert-manager.io
            kinds:
            - CertificateRequest
          - apiGroups:
            - cilium.io
            kinds:
            - CiliumIdentity
            - CiliumEndpoint
            - CiliumEndpointSlice
          - apiGroups:
            - kyverno.io
            - reports.kyverno.io
            - wgpolicyk8s.io
            kinds:
            - PolicyReport
            - ClusterPolicyReport
            - EphemeralReport
            - ClusterEphemeralReport
            - AdmissionReport
            - ClusterAdmissionReport
            - BackgroundScanReport
            - ClusterBackgroundScanReport
            - UpdateRequest
  EOT
  ]

  # The full value set, spelled out rather than relying on --reuse-values, so
  # that new chart defaults take effect on a chart major.
  #
  # server.insecure because Traefik terminates TLS. Without it https runs on
  # https and the ingress returns 502.
  #
  # The metrics flags only add the three *-metrics Services; the components
  # listen on those ports either way, so enabling them restarts nothing. The
  # matching ServiceMonitors deliberately stay out of this release and live in
  # kubernetes-homelab/manifests/argocd/: their CRD arrives with
  # kube-prometheus-stack, which ArgoCD itself rolls out, so a chart that
  # created them here would fail on a fresh bootstrap.
  set = [
    {
      name  = "global.domain"
      value = var.argocd_domain
    },
    {
      name  = "controller.metrics.enabled"
      value = "true"
    },
    {
      name  = "repoServer.metrics.enabled"
      value = "true"
    },
    {
      name  = "server.metrics.enabled"
      value = "true"
    },
    {
      name  = "configs.cm.url"
      value = "https://${var.argocd_domain}"
    },
    {
      name  = "configs.params.server\\.insecure"
      value = "true"
    },
  ]
}

# The root Application is not rolled out from here: a kubernetes_manifest needs
# its CRD at plan time, and the Application CRD only exists once this release is
# installed.
output "next_step" {
  description = "Manual step after the apply"
  value       = <<-EOT

    ArgoCD is up. Roll out the root app:

      KUBECONFIG=${var.kubeconfig_path} \
        kubectl apply -f ../../kubernetes-homelab/bootstrap/root-app-talos.yaml

    Initial admin password:

      KUBECONFIG=${var.kubeconfig_path} kubectl -n argocd get secret \
        argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d

  EOT
}
