variable "kubeconfig_path" {
  description = "kubeconfig of the Talos cluster. Generated by talhelper, gitignored, contains only this cluster."
  type        = string
  default     = "../../kubernetes-homelab/talos/clusterconfig/kubeconfig"
}

variable "argocd_chart_version" {
  description = "argo-cd Helm chart version"
  type        = string
  # renovate: datasource=helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
  default = "10.3.3"
}

variable "argocd_domain" {
  description = "Hostname for the ArgoCD UI"
  type        = string
  default     = "argocd.elmstreet79.de"
}
